[package]
name = "amoeba"
version = "0.2.0"
edition = "2021"
description = "⚡ Amoeba Framework CLI - Blazing fast scaffolding for Go & TypeScript apps"
authors = ["dron <https://github.com/Sruhvx-jpg>"]

[dependencies]
clap = { version = "4.6", features = ["derive", "color"] }
inquire = "0.9"
colored = "3.1"
indicatif = "0.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
reqwest = { version = "0.13", features = ["blocking", "json"] }
walkdir = "2.5"
regex = "1.11"
